### ISSUE TITLE
[BUG] Segmentation fault in DQ_Kinematics::line_to_line_distance_jacobian

### ISSUE THREAD

**Issue by DanSJohnson** [dqrobotics/cpp#65] opened 2024-03-25 17:22 UTC
**************************
### Code of Conduct
_By submitting this report you automatically agree that you've read and accepted the following conditions._ 
- Support for DQ Robotics is given voluntarily and it's not the developers' role to educate and/or convince anyone of their vision.
- Any possible response and its timeliness will be based on the relevance, accuracy, and politeness of a request and the following discussion.
- If a DQ Robotics member replies, the user must let them know if their response solves their issue or not. 
- Any suggestion/advice/request made by anyone, as well intentioned as they might be, might not be incorporated into DQ Robotics.
*************************

**Bug description**
The function DQ_Kinematics::line_to_line_distance_jacobian appears to contain a bug which causes a segmentation fault. I beleive the source of the bug is a mistake on line 647 of the file [DQ_Kinematics.cpp](https://github.com/dqrobotics/cpp/blob/master/src/robot_modeling/DQ_Kinematics.cpp). This line reads:
```C++
const MatrixXd Jcrossdual    = Jcross.block(5,8,4,DOFS);
```
which attempts to extract a block of size $4 \times \text{DOFS}$ starting at element $(5,8)$. The matrix `Jcross` has 8 rows and $\text{DOFS}$ columns, meaning this request cannot be fulfilled and a segfault ensues. 

I believe this line should instead read:
```C++
const MatrixXd Jcrossdual    = Jcross.block(4,0,4,DOFS);
```

**To Reproduce**

*Code*

```C++
#include <Eigen/Core>
#include <dqrobotics/robot_modeling/DQ_Kinematics.h>
#include <dqrobotics/robots/FrankaEmikaPandaRobot.h>

using namespace DQ_robotics;

DQ_SerialManipulatorMDH franka=FrankaEmikaPandaRobot::kinematics();
DQ pose=franka.fkm(VectorXd::Zero(franka.get_dim_configuration_space()));
MatrixXd pose_jacobian=franka.pose_jacobian(VectorXd::Zero(franka.get_dim_configuration_space()));;
DQ robot_line=i_;
DQ workspace_line=j_;
MatrixXd line_jacobian=DQ_Kinematics::line_jacobian(pose_jacobian, pose, robot_line);

MatrixXd final_jacobian = DQ_Kinematics::line_to_line_distance_jacobian(line_jacobian, robot_line, workspace_line);

std::cout<<final_jacobian <<std::endl;

```
*Output*
```
/usr/include/eigen3/Eigen/src/Core/Block.h:147: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index, Eigen::Index, Eigen::Index, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = -1; int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `startRow >= 0 && blockRows >= 0 && startRow <= xpr.rows() - blockRows && startCol >= 0 && blockCols >= 0 && startCol <= xpr.cols() - blockCols' failed.
Aborted (core dumped)
```

**Expected behavior**
- The line to line distance Jacobian should be printed to the terminal. 

*Expected output*
```
0  0  0  0  0  0  0
```

**Environment:**
 - OS: WSL install of Ubuntu 18.04 LTS, running on Windows 10 Enterprise Edition.
 - dqrobotics version: Current master branch at time of writing (comit [77acf9a](https://github.com/dqrobotics/cpp/commit/77acf9a42875ffb69e9f48f98f3950f9d7242c0e) )

**Comment by juanjqo** [comment] 2024-03-26 02:19
Hi @dqrobotics/developers , I was able to reproduce the issue that @DanSJohnson mentioned. I also think Jcrossdual should be 
```cpp
const MatrixXd Jcrossdual    = Jcross.block(4,0,4,DOFS);
```

Despite the bug is indeed present in Python by construction, interestingly, there is no execution error there, maybe because is a template error(?). 

Minimal example in Python:

```python
from dqrobotics import DQ
from dqrobotics.robot_modeling import DQ_Kinematics
from dqrobotics.robots import FrankaEmikaPandaRobot
import numpy as np


def main() -> None:
    franka=FrankaEmikaPandaRobot.kinematics()
    q = np.zeros(franka.get_dim_configuration_space())
    pose=franka.fkm(q)
    pose_jacobian=franka.pose_jacobian(q)
    robot_line= DQ.i
    workspace_line=DQ.j
    line_jacobian=DQ_Kinematics.line_jacobian(pose_jacobian, pose, robot_line);
    final_jacobian = DQ_Kinematics.line_to_line_distance_jacobian(line_jacobian, robot_line, workspace_line)


if __name__ == "__main__":
    main()
```

Output:
```shell
[[-0. -0.  0.  0. -0.  0.  0.]]
```

I modified the code in my local tests. I added some prints in the C++ side to see them on Python. 

```cpp
MatrixXd DQ_Kinematics::line_to_line_distance_jacobian(const MatrixXd& line_jacobian, const DQ& robot_line, const DQ& workspace_line)
{
  // ...
  //Cross product Jacobian
    const MatrixXd Jcross        = 0.5*(haminus8(l_dq)-hamiplus8(l_dq))*line_jacobian;
    const MatrixXd Jcrossprimary = Jcross.block(0,0,4,DOFS);
    const MatrixXd Jcrossdual    = Jcross.block(5,8,4,DOFS);
    std::cout<<"Jcross"<<std::endl;
    std::cout<<Jcross<<std::endl;
    std::cout<<"Jcrossprimary"<<std::endl;
    std::cout<<Jcrossprimary<<std::endl;
    std::cout<<"Jcrossdual"<<std::endl;
    std::cout<<Jcrossdual<<std::endl;
    //...
}
```

The same python code (without printing `final_jacobian`) results in:

```shell
Jcross
           0            0            0            0            0            0            0
           0            1 -2.22045e-16           -1  2.22045e-16           -1 -2.22045e-16
           0            0            0            0            0            0            0
           0            0            0            0            0            0            0
           0            0            0            0            0            0            0
     -0.0413  -2.5289e-18      -0.0413 -7.58056e-18      -0.0413  -2.5289e-18       0.1293
           0            0            0            0            0            0            0
      -0.926 -1.65111e-17       -0.926 -9.68912e-17       -0.926 -9.68912e-17        0.926
Jcrossprimary
           0            0            0            0            0            0            0
           0            1 -2.22045e-16           -1  2.22045e-16           -1 -2.22045e-16
           0            0            0            0            0            0            0
           0            0            0            0            0            0            0
Jcrossdual
           0 1.08195e-309 1.08195e-309 1.28796e-309            0            0            0
1.08195e-309 1.08195e-309            0            0 1.28797e-309            0            0
1.08195e-309 1.08195e-309            0            0 1.28797e-309            0            0
1.08195e-309 1.08195e-309            0            0            0            0            0
```
This is, there is not an execution error in Python, instead, the Jcrossdual matrix is composed of weird values. I was wondering if you know the reason of such behavior?


Best regards, 

Juancho

**Comment by mmmarinho** [comment] 2024-03-26 10:09
Thanks, @DanSJohnson,

Please open a pull request with a fix because it's only in the CPP side and affects a single line.

@DanSJohnson, @juanjqo 

What happened in CPP was not a segmentation fault, as you can see from @DanSJohnson output. The program was `Aborted` because it failed the assertion checking the bounds of the matrix. 
https://en.cppreference.com/w/cpp/utility/program/abort
I'm sure that if you check the header file described in the error output you'll find it being called around line 147.

The same bounds are not being checked in the Python-compiled version and that can be for a large number of reasons. It depends on the preprocessor directives, how the templates are being unfolded for the library generation, compilation flags, and so on.

In addition, as you have noticed, simply assessing memory out of bounds of a particular matrix does not necessarily result in a segmentation fault. The size of a matrix is an abstraction in a higher level. A segmentation fault is a low-level, program-wide, memory access permission error so, if you're (un)lucky enough, you'll access memory of other chunks of the program, resulting in complete nonsense but no errors.

**Comment by DanSJohnson** [comment] 2024-03-26 10:14
Hi @juanjqo and @mmmarinho. Thank you both for your responses. I will open a pull request shortly.

**Closed** 2024-03-26 11:28 UTC
Labels: bug
